file_format: "1"
id: lily58
name: LILY58
type: shield
url: https://github.com/kata0510/Lily58
requires: [Nice!Nano]
exposes: [nice_view_spi]
features:
  - keys
  - display
  - underglow
siblings:
  - lily58_left
  - lily58_right
