manifest:
# test
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: gpeye
      url-base: https://github.com/GPeye

      #- name: mctechnology17
    #  url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

    - name: hammerbeam-slideshow
      remote: gpeye
      revision: main

      # - name: zmk-nice-oled
   #   remote: mctechnology17
   #   revision: main
  self:
    path: config
